security.user:
  name: user
  password: password
space.name: dev
flyway.schemas: aladin
spring.profiles.active: postgres

---
spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/db-abc?user=abc&password=def

---
spring:
  profiles: h2inmemory
  datasource:
    username: dbuser
    password: dbpass
